---
- name: copy rtl8812au interface
  become: yes
  template:
    src: interface.ini
    dest: /etc/network/interfaces.d/enx{{ rtl8812au_mac }}
- name: copy rtl8812au wpa supplicant template
  become: yes
  template:
    src: wpa_supplicant.conf.ini
    dest: /etc/wpa_supplicant/wpa_supplicant-enx{{ rtl8812au_mac }}.conf