---
- name: install rtl8812au dependencies
  become: yes
  apt:
    state: present
    name: [
      'raspberrypi-kernel-headers',
      'git',
      'build-essential',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed