---
# tasks file for pi_driver_rtl8812au
- name: check rtl8812au module exist
  stat:
    path: /lib/modules/{{ ansible_kernel }}/kernel/drivers/net/8812au.ko
  register: rtl8812au_check
- include: compile_rtl8812au.yml
  when: not rtl8812au_check.stat.exists
- include: configure_Debian.yml
  when: ansible_os_family == 'Debian'
- name: load module on startup
  lineinfile:
    path: /etc/modules
    line: 8812au
    state: "{{ 'present' if rtl8812au_load_module_on_startup else 'absent' }}"